{-# LANGUAGE NoOverloadedStrings #-}
module SandBoxEffect where

import CallSpecs.CpOne ()
import CallSpecs.CpManyToDir ()
import CallSpecs.Date
import CallSpecs.FindCases ()
import CallSpecs.GitInit ()
import CallSpecs.GitInitExit1 ()
import CallSpecs.GitSubcases ()
import System.Process.Quick
import System.Process.Quick.Prelude

main :: IO ()
main = do
  startedAt <- currentTime
  $(discoverAndVerifyCallSpecs (fromList [SandboxValidate]) 3)
  endedAt <- currentTime
  putStrLn $ "Execution of expr generated by discoverAndVerifyCallSpecs took " <>
    show (endedAt `diffUTCTime` startedAt)
  callProcess $ Date $$(refineTH "+%Y")
